create table if not exists spotify_playlist_track_attributions (
    id bigint generated by default as identity primary key,
    playlist_id varchar(128) not null,
    track_id varchar(64) not null,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_spotify_playlist_track_attributions_playlist_track unique (playlist_id, track_id),
    constraint fk_spotify_playlist_track_attributions_user
        foreign key (user_id) references users(id)
);

create index if not exists idx_spotify_playlist_track_attributions_playlist_track
    on spotify_playlist_track_attributions (playlist_id, track_id);
