spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  task:
    scheduling:
      enabled: false

# App-level safe defaults
app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000

# Strong test secret (>= 256 bits). Not strictly needed since we mock JwtService,
# but harmless to keep for any full-context tests.
jwt:
  secret: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
