name: CI

on:
  push:
    branches: [ "**" ]
    # paths: [ "backend/**", ".github/workflows/**" ]  # <- uncomment if monorepo
  pull_request:
    branches: [ "**" ]
    # paths: [ "backend/**", ".github/workflows/**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      MAVEN_OPTS: -Xmx2g
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build & test
        run: mvn -B -ntp verify

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          if-no-files-found: ignore

      - name: Upload JaCoCo coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: "**/target/site/jacoco/**"
          if-no-files-found: ignore
